# Generated by Django 3.0.5 on 2021-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNew',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userScore', models.IntegerField()),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('rang', models.CharField(max_length=15)),
            ],
        ),
    ]
