# Generated by Django 3.0.5 on 2021-06-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.CharField(max_length=20),
        ),
    ]
